import { Product, ProductLine } from '@/types/product';

export const PRODUCTS: Product[] = [
  {
    id: 'essential-rect-m',
    name: 'VELORA Essential Box - Rechteckig M',
    line: 'essential',
    form: 'rectangular',
    size: 'M',
    price: 14.99,
    image: '/products/essential-rect-m.jpg',
    description: 'Praktische Vorratsbox aus transparentem Kunststoff mit minimalistischem Design',
    features: ['Transparenter Kunststoff', 'Holzdeckel', 'Luftdicht', 'Spülmaschinenfest'],
    dimensions: { width: 20, height: 12, depth: 10 },
  },
  {
    id: 'classic-rect-m',
    name: 'VELORA Classic Box - Rechteckig M',
    line: 'classic',
    form: 'rectangular',
    size: 'M',
    price: 34.99,
    image: '/products/classic-rect-m.jpg',
    description: 'Premium Vorratsbox mit hochwertigen Materialien und elegantem Design',
    features: ['Hochwertiger Kunststoff', 'Echtholz-Deckel', 'Präzisionsverschluss', 'Design Award'],
    dimensions: { width: 20, height: 12, depth: 10 },
  },
  {
    id: 'atelier-rect-m',
    name: 'VELORA Atelier Box - Rechteckig M',
    line: 'atelier',
    form: 'rectangular',
    size: 'M',
    price: 99.99,
    image: '/products/atelier-rect-m.jpg',
    description: 'Exklusive Vorratsbox aus Glas und Eiche mit Push-to-Open Mechanismus',
    features: ['Borosilikat-Glas', 'Eicheholz', 'Push-to-Open', 'Handgefertigt'],
    isSmart: false,
    dimensions: { width: 20, height: 12, depth: 10 },
  },
  {
    id: 'smart-rect-m',
    name: 'VELORA Smart Box - Rechteckig M',
    line: 'classic',
    form: 'rectangular',
    size: 'M',
    price: 84.98,
    image: '/products/smart-rect-m.jpg',
    description: 'Intelligente Vorratsbox mit Gewichtsmessung und App-Integration',
    features: ['Wägezelle integriert', 'Bluetooth 5.0', 'App-gesteuert', 'USB-C Ladeport'],
    isSmart: true,
    dimensions: { width: 20, height: 12, depth: 10 },
  },
];

export const SETS = [
  {
    id: 'set-essential-starter',
    name: 'VELORA Essential Starter',
    description: '4 praktische Boxen zum Einstieg',
    items: ['essential-rect-m', 'essential-rect-m', 'essential-rect-m', 'essential-rect-m'],
    price: 49.99,
    savings: 10,
  },
  {
    id: 'set-classic-kitchen',
    name: 'VELORA Classic Kitchen',
    description: '4 Premium Boxen + Organizer',
    items: ['classic-rect-m'],
    price: 159.99,
    savings: 20,
  },
  {
    id: 'set-smart-starter',
    name: 'VELORA Smart Starter',
    description: '4 smarte Boxen mit App',
    items: ['smart-rect-m'],
    price: 279.99,
    savings: 50,
  },
];
